name: 'Build Eleventy (11ty)'
description: 'Builds 11ty without using docker or root permissions'
author: 'extrawitz'
inputs: 
  args:
   description: 'arguments to be used, when running "eleventy"'
   required: false
runs:
  using: "composite"
  steps:
   - name: Install npm dependencies from .eleventy.js
     run: npm install
     shell: bash
   - name: Build the website
     run: npm install
     shell: bash