name: Eleventy Build
description: Build 11ty (dockerless)
on: [push]
jobs:
  build_deploy:
  runs-on: ubuntu-18.04, self-hosted
  steps:
   - name: Checkout last commit of repository
   - uses: actions/checkout@v3
   - name: Install 11ty and build website
     uses: extrawitz/11ty-dockerless-build
   - name: Deploy
     uses: peaceiris/actions-gh-pages@v3
     with:
      publish_dir: public
      publish_branch: website
      github_token: ${{ secrets.PSA }}